[tools]
rust = "latest"

[env]
GH_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSEZtR2ZIbFRNdjR6alJaM1J0UmwyeXVVbzF3S2Vpb0xnQzdGWS9GbnpJCmdBNVEraitGTHBIb2FiMmNHNnp5NkduN0h4YmhkTkRPeWo0SU10Tkx3RkkKLT4gfTMtZ3JlYXNlIEBhdTNbYQpMczZ4cHVOK3dHWHI1Vkh4Y2NjbmlxdlJFT05PR093T2o0RE5lNmNpVTBXUWpQSEpkK2ZRRTNaU0hHOVp3djZ1CkpKenViWmxqZU1UQ1NkdG44S3U5Ci0tLSBWU0RoSytkUTZEMjZSQ3BjckZwblVzcmJ6cXlTUmRvdkJyc2hpVDMvUWxzCkMyjjU88+DOIJxheNP0wWkBsHDzSjItiydVzEsh9r1mF0cBNH2P5hw2U+4j0ETIvI7OskO7MDvL6l6Pd65OadGMUXAAtcEQlUMhIzsgm6YYJoSaRZQq9AV03PIPX5z9qphobeIL748xt6axAg6Sy57lNwoaDws488Hf7uBK" }
